=== based2/minuteProject/minuteKernel/src/main/config/mp-template-config.xsd
<xs:schema id="target" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://minuteproject.sf.net/xsd/mp-template-config"
	targetNamespace="http://minuteproject.sf.net/xsd/mp-template-config"
	elementFormDefault="qualified">

	<xs:element name="target" type="target">
	</xs:element>

	<xs:complexType name="target">
		<xs:sequence>
			<xs:element name="architecture-target" type="architecture-target"
				minOccurs="0" maxOccurs="unbounded">
			</xs:element>
			<xs:element name="plugin" type="plugin" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
			<xs:element name="template-target" type="template-target"
				minOccurs="0" maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="architecture-target">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="description" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="plugin">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="className" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="property">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="value" type="xs:string" />
		<xs:attribute name="tag" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="template">
		<xs:sequence>
			<xs:element name="property" type="property" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="templateFileName" type="xs:string" />
		<xs:attribute name="subdir" type="xs:string" />
		<xs:attribute name="outputsubdir" type="xs:string" />
		<xs:attribute name="technicalPackage" type="xs:string" />
		<xs:attribute name="add-model-name" type="xs:string" />
		<xs:attribute name="add-model-dir-name" type="xs:string" />
		<xs:attribute name="file-extension" type="xs:string" />
		<xs:attribute name="file-prefix" type="xs:string" />
		<xs:attribute name="file-suffix" type="xs:string" />
		<xs:attribute name="entity-specific" type="xs:string" />
		<xs:attribute name="package-specific" type="xs:string" />
		<xs:attribute name="model-specific" type="xs:string" />
		<xs:attribute name="check-template-to-generate" type="xs:string" />
		<xs:attribute name="is-template-to-generate-method" type="xs:string" />
		<xs:attribute name="field-specific" type="xs:string" />
		<xs:attribute name="file-name-builder-plugin" type="xs:string" />
		<xs:attribute name="file-name-builder-method" type="xs:string" />
		<xs:attribute name="application-specific" type="xs:string" />
		<xs:attribute name="package-root" type="xs:string" />
		<xs:attribute name="add-technical-dir-name" type="xs:string" />
		<xs:attribute name="add-business-package-dir-name=" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="template-target">
		<xs:sequence>
			<xs:element name="template" type="template" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="libdir" type="xs:string" />
		<xs:attribute name="tool" type="xs:string" />
		<xs:attribute name="outputdir" type="xs:string" />
		<xs:attribute name="package-root" type="xs:string" />
		<xs:attribute name="belongToPackage" type="xs:string" />
		<xs:attribute name="templatedir" type="xs:string" />
	</xs:complexType>

</xs:schema>

=== based2/minuteProject/minuteKernel/src/main/config/mp-template-config-ABL-OPENXAVA.xml
<target name="ABL framework"
xmlns="http://minuteproject.sf.net/xsd/mp-template-config" 
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:schemaLocation="mp-template-config.xsd">
	<architecture-target name="ABL" description="Automated Business Logic architecture">
	</architecture-target>	

    <plugin name="ablUtils" className="net.sf.minuteProject.utils.rule.AblUtils"></plugin>

	<template-target 
    	name="ABL"
		libdir="lib/ABL_LIB.vm"
		outputdir="src">
		<!-- ABL beans -->	
		<template name="ABL.Logic" templateFileName="ABL.Logic.vm" 
			subdir="" outputsubdir="" technicalPackage="businesslogic"
			file-extension="groovy" file-prefix="" file-suffix="Logic" 
            check-template-to-generate="true" 
            is-template-to-generate-method="ablUtils.isToGenerateBasedRulePresence"
			has-updatable-nature="true"
			scope-specific-value="entity">
			<property name="DomainEntityUMLTemplate" value="OpenxavaDomainObjectUML" ></property>  
		</template>	
		
		<template name="ABL.LogicBase" templateFileName="ABL.LogicBase.vm" 
			subdir="" outputsubdir="" technicalPackage="businesslogic"
			file-extension="groovy" file-prefix="" file-suffix="BizLogicBase" 
			has-updatable-nature="true" add-model-name="false"
			scope-specific-value="model" >
		</template>	

        <template name="ABL.ConstraintExceptionTranslatorJCA" templateFileName="ABL.ConstraintExceptionTranslatorJCA.vm" 
            subdir="" outputsubdir="" technicalPackage="businesslogic"
            file-extension="java" file-prefix="" file-suffix="ConstraintExceptionTranslatorJCA" 
            has-updatable-nature="true" add-model-name="false"
            scope-specific-value="model" >
        </template> 
        
        <template name="ABL.ConstraintViolation" templateFileName="ABL.ConstraintViolation.vm" 
            subdir="" outputsubdir="" technicalPackage="businesslogic"
            file-extension="java" file-prefix="" file-suffix="AblConstraintViolation" 
            has-updatable-nature="true" add-model-name="false"
            scope-specific-value="model" >
        </template> 
        
    </template-target>
    
	<template-target 
    	name="ABL"
		outputdir="src"
		package-root="">

		<template name="ABL.Config" templateFileName="ABL.Config.vm" 
			subdir="" outputsubdir="" technicalPackage="" add-model-dir-name="false"
			file-extension="properties" file-prefix="" file-suffix="ABLConfig" 
			has-updatable-nature="true" add-model-name="false"
			application-specific="true" >
			<property name="DomainEntityUMLTemplate" value="OpenxavaDomainObjectUML" ></property>    
		</template>

		<template name="ABL.Logging" templateFileName="ABL.Logging.vm" 
			subdir="" outputsubdir="" technicalPackage="" add-model-dir-name="false"
			file-extension="properties" file-prefix="" file-suffix="ABL_logging" 
			has-updatable-nature="true" add-model-name="false"
			application-specific="true" >
		</template>

    </template-target>
</target>

=== based2/minuteProject/minuteKernel/src/main/config/mp-template-config-bsla-LIB-features.xml
<target name="Lib and plugin"
xmlns="http://minuteproject.sf.net/xsd/mp-template-config" 
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:schemaLocation="mp-template-config.xsd">		
	<architecture-target name="libraries" description="libraries"/>	
	<plugin name="criteriaUtils" className="net.sf.minuteProject.utils.criteria.CriteriaUtils"></plugin>
	<plugin name="schemaUtils" className="net.sf.minuteProject.plugin.database.SchemaUtils"></plugin>
	<plugin name="referenceDataUtils" className="net.sf.minuteProject.plugin.data.ReferenceDataUtils"></plugin>
	<plugin name="restrictedCodeUtils" 	className="net.sf.minuteProject.utils.code.RestrictedCodeUtils"></plugin>
	<plugin name="mavenUtils" className="net.sf.minuteProject.plugin.maven.MavenUtils"></plugin>	
	<template-target 
		libdir="lib/BslaLibrary.vm,lib/Maven_LIB.vm,lib/JPA_LIB.vm"
		tool="velocity"
		outputdir="src/test/java"
		belongToPackage="true">					
	</template-target>		

</target>
